### ISSUE TITLE
Content syndicate isn't bringing in <p> tags within the content area

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/WSUWP-Content-Syndicate#63]
As illustrated on [hub.wsu.edu/slocker/](https://hub.wsu.edu/slocker/) and [research.wsu.edu](https://research.wsu.edu) it appears that paragraph tags aren't coming through the Content syndicate. In output="full" headers do come through.

**Comment by jeremyfelt** [comment]
After #58, WSUWP Content Syndicate makes local requests rather than remote HTTP requests when it knows it's on the same multisite installation as the other site. The Spine Parent Theme removes `wpautop` when processing its output as it relies on each of the individual sections to take care of that. So... when WSUWP Content Syndicate makes a local request as part of the page builder template, `wpautop` does not fire.

We're fixing upstream in See: https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/pull/322 to ensure local items have the filter applied as needed.
